name: Run Tests

on:
  push:
    branches: [ main, refactor-food-serving-structure ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'
    
    - name: Restore dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Test
      run: dotnet test --no-build --configuration Release --verbosity normal --logger "console;verbosity=detailed"
      
    - name: Run executable smoke test
      run: |
        cd Executable
        echo "n" | timeout 5s dotnet run --no-build --configuration Release || true
        # Check that the program produces expected output
        echo "n" | timeout 5s dotnet run --no-build --configuration Release | grep -q "grams brown rice" && echo "✓ Program produces expected output"